library(ggplot2)
library(plotly)

SensitivityPlot <-function(rank=T,folder){
  load(paste0(folder,"SEIR-sensitivity.RData"))
  # Then, we read all the trajectories generated saving them in a list called
  # ListTraces. List that will be rewritten as a data frame in order to use ggplot.
  # ConfigID represents the initial condition associated to each trajectory,
  # which was generated by using the function implemented in the file Functions.R .
  
  listFile<-list.files(folder,
                       pattern = ".trace")
  
  configID<-t(sapply(1:length(listFile),
                     function(x){
                       return(c(x,config[[1]][[x]][[3]]))
                     }) )
  
  id.traces<-as.numeric(gsub("[^[:digit:].]", "",listFile) )
  
  if(rank){
    load(paste0(folder,"ranking_SEIR-sensitivity.RData"))
  }else{
    rank <- data.frame(measure = 0 , id = id.traces)
  }
  
  reference <- as.data.frame(read.csv("Input/reference_data.csv",
                                      header = FALSE,
                                      sep = ""))
  
  ListTraces<-lapply(id.traces,
                     function(x){
                       trace.tmp=read.csv(paste0(
                         folder,"/SEIR-sensitivity-",
                         x,
                         ".trace"), sep = "")
                       trace.tmp=data.frame(trace.tmp,ID= x, name=paste0("SEIR-sensitivity-", x, ".trace"), rank = rank[which(rank[,2]==paste0("SEIR-sensitivity-", x, ".trace")), 1])
                       return(trace.tmp)
                     })
  
  rank2<-lapply(id.traces,
                function(x){
                  recovery<-config[[7]][[x]][[3]]
                  infection<-config[[6]][[x]][[3]]
                  become_infectious<-config[[5]][[x]][[3]]
                  rnk.tmp=data.frame(ID=x,distance = rank$measure[which(rank[,2]==paste0("SEIR-sensitivity-", x, ".trace"))],rec_rate=recovery, inf_rate=infection, bec_inf_rate=become_infectious)
                  return(rnk.tmp)
                })
  
  rank2 <- do.call("rbind", rank2)
  traces <- do.call("rbind", ListTraces)
  
  plI<-ggplot( )+
    geom_line(data=traces,
              aes(x=Time,y=I,group=ID,col=rank))+
    geom_line(data=reference,
              aes(x=V1,y=V2),
              col="red")+
    theme(axis.text=element_text(size=18),
          axis.title=element_text(size=20,face="bold"),
          legend.text=element_text(size=18),
          legend.title=element_text(size=20,face="bold"),
          legend.position="right",
          legend.key.size = unit(1.3, "cm"),
          legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="I",col="Distance")
  
  plI_best<-ggplot( )+
    geom_line(data=traces[which(traces$name == rank$id[which(rank$measure == min(rank$measure))]),],
              aes(x=Time,y=I,group=ID,col=rank))+
    geom_line(data=reference,
              aes(x=V1,y=V2),
              col="red")+
    theme(axis.text=element_text(size=18),
          axis.title=element_text(size=20,face="bold"),
          legend.text=element_text(size=18),
          legend.title=element_text(size=20,face="bold"),
          legend.position="right",
          legend.key.size = unit(1.3, "cm"),
          legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="I",col="Distance")
  
  plE<-ggplot( )+
    geom_line(data=traces,
              aes(x=Time,y=E,group=ID,col=rank))+
    theme(axis.text=element_text(size=18),
          axis.title=element_text(size=20,face="bold"),
          legend.text=element_text(size=18),
          legend.title=element_text(size=20,face="bold"),
          legend.position="right",
          legend.key.size = unit(1.3, "cm"),
          legend.key.width = unit(1.3,"cm") )+
    labs(x="Weeks", y="E",col="Distance")
  
  pl <- plot_ly(rank2, x = ~bec_inf_rate, y = ~inf_rate, z = ~rec_rate, color = ~distance, colors = c("black","deepskyblue2","cyan"))
  
  return(list(TrajI =plI, TrajI_best= plI_best, TrajE = plE, Points = pl))
}